name: Bitcoin Price Monitor

on:
  schedule:
    # Runs every 5 minutes (minimum interval for GitHub Actions)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  monitor-bitcoin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Bitcoin Monitor
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python main.py
    
    - name: Commit and push data (if needed)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "Update Bitcoin price data - $(date)"
          git push
        fi